name: 'Laravel Pint Github Action'
description: 'Use Laravel Pint to clean your code'
author: 'Steve Barbera'
inputs: 
  preset:
    description: 'The Pint preset you would like to use'
    required: false
    default: psr12
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.preset }}
